url=https://rezzqa6.its-cs.com/Auth/Login?returnUrl=%2FDashboard
email =itsindiaqa6@gmail.com

password =Netm0an@1
browser=chrome

timeZone= (GMT+01:00) Europe/London

firstName = Automation

lastName = Test

emailID=c3834717@gmail.com

location =Testing

parentLocation = Testing

timeout=20

theme=R&R

language = english (US)

Zoom=100%

roomName=Testing1 (Testing)

location=Testing

duration=7

prepration =5

deskname=Desk1 (Testing)

addname=computer1

addID=computer1

defaultduration=6

prepartiontime=6

noshowwaitTime=10

level1Warning=6

level2WarningMessage=7

level3Warning=8

inactivityTimeout=1439

lockTimeout=1439

location=Testing

startTime=3:15 PM

StartTime1 =3:40 PM

StartTime2= 4:00 PM

Pleasechoose=Test Tags2

DeskTags= Chandrika user Tags

RoomTags= Automation

ComputerTags= Computer

Locations= All

UsersTag = Automation Tags

AdminPolicy = All rules

Name = GuestUser

Userprefix = @

Numberoffigure=6

length=7

Activation = on first login 

period= 1 month

BookingType =past

periods=day

context =Tags

UserName =Desktop

Password1 =Chandu.30@


